package server

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

const renewalWrapperPath = "/usr/local/bin/ssl_renewal.sh"

func (s *Server) installRenewalWrapper(ctx context.Context, adminEmail string, warnDays int) error {
	script := fmt.Sprintf(`#!/bin/bash
# ============================================================================
# MailX SSL Renewal Wrapper
# Generated by MailX Admin on %s
# Do not edit by hand — regenerate from the panel.
# ============================================================================

ADMIN_EMAIL="%s"
WARN_DAYS=%d
DOMAIN_FILE="/usr/local/roundcube_mail_domain.txt"
FAIL_LOG="/var/log/mailx/ssl_renewal_failures.log"
STATE_DIR="/usr/local/mailx_state"

mkdir -p "$(dirname "$FAIL_LOG")" "$STATE_DIR"

DOMAIN=$(cat "$DOMAIN_FILE" 2>/dev/null | tr -d '[:space:]')
HOSTNAME=$(hostname)

log_fail() {
    echo "[$(date '+%%Y-%%m-%%d %%H:%%M:%%S')] $1" >> "$FAIL_LOG"
}

send_mail() {
    local subject="$1"
    local body="$2"
    if [ -n "$ADMIN_EMAIL" ]; then
        echo -e "$body" | mail -s "$subject" \
            -a "From: admin@${DOMAIN:-localhost}" "$ADMIN_EMAIL" 2>/dev/null || true
    fi
}

# ---- Step 1: Attempt renewal ----------------------------------------------
CERTBOT_LOG=$(mktemp)
if certbot renew --quiet \
        --deploy-hook "systemctl reload postfix dovecot apache2" \
        > "$CERTBOT_LOG" 2>&1; then
    RENEW_RC=0
else
    RENEW_RC=$?
fi

if [ "$RENEW_RC" -ne 0 ]; then
    TODAY=$(date +%%Y-%%m-%%d)
    LAST_ALERT_FILE="$STATE_DIR/ssl_last_fail_alert"
    LAST_ALERT=$(cat "$LAST_ALERT_FILE" 2>/dev/null)
    if [ "$LAST_ALERT" != "$TODAY" ]; then
        echo "$TODAY" > "$LAST_ALERT_FILE"
        log_fail "certbot renew failed (rc=$RENEW_RC)"
        send_mail "[$HOSTNAME] SSL renewal FAILED for ${DOMAIN:-unknown}" \
"SSL RENEWAL FAILURE — ACTION REQUIRED

Server    : $HOSTNAME
Domain    : ${DOMAIN:-unknown}
Time      : $(date '+%%Y-%%m-%%d %%H:%%M:%%S')

Certbot output (last 30 lines):
-------------------------------------------
$(tail -n 30 "$CERTBOT_LOG")
-------------------------------------------

MANUAL RENEWAL:
   certbot renew --force-renewal
   systemctl reload postfix dovecot apache2

Panel: SSL → renew now"
    fi
    rm -f "$CERTBOT_LOG"
    exit 1
fi
rm -f "$CERTBOT_LOG"

# ---- Step 2: Warn if getting close ----------------------------------------
if [ -n "$DOMAIN" ] && [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    END_DATE=$(openssl x509 -enddate -noout \
        -in "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" 2>/dev/null | cut -d= -f2)
    if [ -n "$END_DATE" ]; then
        END_EPOCH=$(date -d "$END_DATE" +%%s 2>/dev/null)
        NOW_EPOCH=$(date +%%s)
        DAYS_LEFT=$(( (END_EPOCH - NOW_EPOCH) / 86400 ))

        if [ "$DAYS_LEFT" -lt "$WARN_DAYS" ] && [ "$DAYS_LEFT" -ge 0 ]; then
            TODAY=$(date +%%Y-%%m-%%d)
            LAST_WARN_FILE="$STATE_DIR/ssl_last_warn_alert"
            LAST_WARN=$(cat "$LAST_WARN_FILE" 2>/dev/null)
            if [ "$LAST_WARN" != "$TODAY" ]; then
                echo "$TODAY" > "$LAST_WARN_FILE"
                send_mail "[$HOSTNAME] SSL cert for ${DOMAIN} expires in $DAYS_LEFT days" \
"SSL CERTIFICATE EXPIRY WARNING

Server     : $HOSTNAME
Domain     : $DOMAIN
Expires    : $END_DATE
Days left  : $DAYS_LEFT (threshold: $WARN_DAYS)

The automatic renewal either failed silently or has not yet run.
Check from the MailX Admin panel: SSL → $DOMAIN → View details."
            fi
        fi
    fi
fi

exit 0
`, time.Now().Format(time.RFC3339), adminEmail, warnDays)

	if err := os.WriteFile(renewalWrapperPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write wrapper: %w", err)
	}

	// Ensure cron entries exist
	if err := ensureCronEntries(ctx); err != nil {
		return fmt.Errorf("cron entries: %w", err)
	}

	return nil
}

func ensureCronEntries(ctx context.Context) error {
	// Read current crontab
	out, _ := exec.CommandContext(ctx, "crontab", "-l").Output()
	current := string(out)

	// Filter existing entries for our script
	var kept []string
	for _, line := range strings.Split(current, "\n") {
		if !strings.Contains(line, "ssl_renewal.sh") {
			kept = append(kept, line)
		}
	}

	kept = append(kept, "17 3 * * * /usr/local/bin/ssl_renewal.sh")
	kept = append(kept, "17 15 * * * /usr/local/bin/ssl_renewal.sh")

	newCrontab := strings.Join(kept, "\n") + "\n"

	cmd := exec.CommandContext(ctx, "crontab", "-")
	cmd.Stdin = strings.NewReader(newCrontab)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("crontab: %w: %s", err, out)
	}
	return nil
}
