package sieve

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/gtmylab/mailx-admin/internal/models"
)

// Generate produces a Sieve script for one user from their rules.
//
// The script is a single "fileinto" pipeline. Rules are evaluated in order.
// Requirements: managesieve (Dovecot Pigeonhole). We require "fileinto",
// "vacation", "imap4flags", and "copy" extensions.
func Generate(rules []models.SieveRule, email string) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by MailX Admin — DO NOT EDIT\n")
	b.WriteString("# Regenerate from the panel to change rules.\n")
	b.WriteString(fmt.Sprintf("# Account: %s\n", email))
	b.WriteString("\n")

	b.WriteString("require [\"fileinto\", \"vacation\", \"imap4flags\", \"copy\", \"envelope\"];\n\n")

	for _, r := range rules {
		if !r.Enabled {
			continue
		}
		switch r.RuleType {
		case "vacation":
			script, err := genVacation(r)
			if err != nil {
				return "", fmt.Errorf("rule %d vacation: %w", r.ID, err)
			}
			b.WriteString(script)
		case "forward":
			script, err := genForward(r)
			if err != nil {
				return "", fmt.Errorf("rule %d forward: %w", r.ID, err)
			}
			b.WriteString(script)
		case "move_folder":
			script, err := genMoveFolder(r)
			if err != nil {
				return "", fmt.Errorf("rule %d move_folder: %w", r.ID, err)
			}
			b.WriteString(script)
		case "discard":
			script, err := genDiscard(r)
			if err != nil {
				return "", fmt.Errorf("rule %d discard: %w", r.ID, err)
			}
			b.WriteString(script)
		case "mark_read":
			script, err := genMarkRead(r)
			if err != nil {
				return "", fmt.Errorf("rule %d mark_read: %w", r.ID, err)
			}
			b.WriteString(script)
		default:
			return "", fmt.Errorf("unknown rule type: %s", r.RuleType)
		}
		b.WriteString("\n")
	}

	b.WriteString("# End of generated rules\n")
	b.WriteString("keep;\n")

	return b.String(), nil
}

func genVacation(r models.SieveRule) (string, error) {
	var cfg struct {
		Subject   string   `json:"subject"`
		Message   string   `json:"message"`
		Days      int      `json:"days"`
		Addresses []string `json:"addresses"`
	}
	if err := json.Unmarshal(r.Config, &cfg); err != nil {
		return "", err
	}
	if cfg.Days <= 0 {
		cfg.Days = 7
	}
	if cfg.Subject == "" {
		cfg.Subject = "Out of office"
	}

	var b strings.Builder
	b.WriteString("# Vacation / out-of-office\n")

	if len(cfg.Addresses) > 0 {
		var quoted []string
		for _, a := range cfg.Addresses {
			quoted = append(quoted, quoteString(a))
		}
		b.WriteString(fmt.Sprintf("if anyof (address :contains [\"from\", \"sender\"] [%s]) {\n",
			strings.Join(quoted, ", ")))
	} else {
		b.WriteString("if true {\n")
	}

	// no reply to mailing lists or bulk mail
	b.WriteString("  if not header :contains \"Precedence\" [\"bulk\", \"list\", \"junk\"] {\n")
	b.WriteString(fmt.Sprintf("    vacation :days %d\n", cfg.Days))
	b.WriteString(fmt.Sprintf("      :subject %s\n", quoteString(cfg.Subject)))
	b.WriteString(fmt.Sprintf("      %s;\n", quoteString(cfg.Message)))
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String(), nil
}

func genForward(r models.SieveRule) (string, error) {
	var cfg struct {
		Address  string `json:"address"`
		KeepCopy bool   `json:"keep_copy"`
	}
	if err := json.Unmarshal(r.Config, &cfg); err != nil {
		return "", err
	}
	if cfg.Address == "" || !strings.Contains(cfg.Address, "@") {
		return "", fmt.Errorf("invalid forward address")
	}

	var b strings.Builder
	b.WriteString("# Forward\n")
	b.WriteString("if true {\n")
	if cfg.KeepCopy {
		b.WriteString(fmt.Sprintf("  redirect :copy %s;\n", quoteString(cfg.Address)))
	} else {
		b.WriteString(fmt.Sprintf("  redirect %s;\n", quoteString(cfg.Address)))
		b.WriteString("  stop;\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func genMoveFolder(r models.SieveRule) (string, error) {
	var cfg struct {
		Folder        string `json:"folder"`
		MatchHeader   string `json:"match_header"`
		MatchContains string `json:"match_contains"`
	}
	if err := json.Unmarshal(r.Config, &cfg); err != nil {
		return "", err
	}
	if cfg.Folder == "" {
		return "", fmt.Errorf("folder required")
	}
	if cfg.MatchHeader == "" {
		cfg.MatchHeader = "Subject"
	}

	var b strings.Builder
	b.WriteString("# Move to folder\n")
	b.WriteString(fmt.Sprintf("if header :contains %s %s {\n",
		quoteString(cfg.MatchHeader), quoteString(cfg.MatchContains)))
	b.WriteString(fmt.Sprintf("  fileinto %s;\n", quoteString(cfg.Folder)))
	b.WriteString("  stop;\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func genDiscard(r models.SieveRule) (string, error) {
	var cfg struct {
		MatchHeader   string `json:"match_header"`
		MatchContains string `json:"match_contains"`
	}
	if err := json.Unmarshal(r.Config, &cfg); err != nil {
		return "", err
	}
	if cfg.MatchHeader == "" {
		cfg.MatchHeader = "From"
	}

	var b strings.Builder
	b.WriteString("# Discard\n")
	b.WriteString(fmt.Sprintf("if header :contains %s %s {\n",
		quoteString(cfg.MatchHeader), quoteString(cfg.MatchContains)))
	b.WriteString("  discard;\n")
	b.WriteString("  stop;\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func genMarkRead(r models.SieveRule) (string, error) {
	var cfg struct {
		MatchHeader   string `json:"match_header"`
		MatchContains string `json:"match_contains"`
	}
	if err := json.Unmarshal(r.Config, &cfg); err != nil {
		return "", err
	}
	if cfg.MatchHeader == "" {
		cfg.MatchHeader = "List-Id"
	}

	var b strings.Builder
	b.WriteString("# Mark as read\n")
	b.WriteString(fmt.Sprintf("if header :contains %s %s {\n",
		quoteString(cfg.MatchHeader), quoteString(cfg.MatchContains)))
	b.WriteString("  addflag \"\\\\Seen\";\n")
	b.WriteString("}\n")
	return b.String(), nil
}

// quoteString returns a Sieve-safe quoted string.
func quoteString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"', '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case '\t':
			b.WriteString("\\t")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
